### ISSUE TITLE
[2024] Update Sponsors section

### ISSUE THREAD

**Issue by HassanBahati** [PyconUg/ug.pycon.org#113]

**Comment by mosespace** [comment]
What should be updated?
I would like to jump on this?

**Comment by HassanBahati** [comment]
hey @mosespace sure, first up you need to get the branch `bump-2024-0-0` and open the pr towards that branch.

let me know incase you need anything

**Comment by HassanBahati** [comment]
for sponsors, we need to have a placeholder as we havent confirmed them yet...happy to guide through
