### ISSUE TITLE
Aligmnet of the button `Buy Ticket`

### ISSUE THREAD

**Issue by mosespace** [PyconUg/ug.pycon.org#13]
I suggest we make the alignment of the button to be uniform![^1]

[^1]: ![image](https://user-images.githubusercontent.com/111237257/228310629-82112c66-6a6b-4c0a-9971-b9632478391a.png)

**Comment by HassanBahati** [comment]
thank you @mosespace for spoting this...
this is what i see on my screen....seems aligned..

nevertheless a pr towards the alignment is welcome 

![image](https://user-images.githubusercontent.com/65954740/228529664-b8056cae-e2f5-4e5b-bc0f-4af70f406124.png)
